server:
  port: 8080
spring:
  datasource:
    mysql:
      jdbc-url: jdbc:mysql://localhost:3232/test
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    oracle:
      jdbc-url: jdbc:oracle:thin:@172.16.43.1:1521/ORCLCDB
      username: SYS as sysdba
      password: oracle
      driver-class-name: oracle.jdbc.driver.OracleDriver
  devtools:
    restart:
      enabled: true  #设置开启热部署
      exclude: "static/**,public/**" ##排除/static，/public
  management: #状态进行监控
    endpoints:
      web:
        exposure:
          include: info, health, beans, env, metrics
mybatis:
  # 映射文件路径
  mapper-locations:
    classpath:mapper/*.xml